name: julep
version: '3'

services:
  agents:
    env_file:
      - .env
    container_name: agents
    depends_on:
      - model
      - cozo
      - worker
    build: 
      context: agents-api/
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    networks:
      - julep-network

  worker:
    env_file:
      - .env
    build:
      context: agents-api/
      dockerfile: Dockerfile.worker
    depends_on:
      - model
      - text-embeddings-inference
      - temporal
    networks:
      - julep-network

  model:
    env_file:
      - .env
    container_name: model
    build: 
      context: model-api/
    ports: 
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    networks:
      - julep-network

  cozo:
    container_name: cozo
    build:
      context: cozo-server/
    ports: 
      - "9070:9070"
    networks:
      - julep-network

  text-embeddings-inference:
    env_file:
      - .env
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-0.6
    ports:
      - "8082:80"
    shm_size: '1gb'
    networks:
      - julep-network

  postgresql:
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:15
    networks:
      - julep-network
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data

  temporal:
    container_name: temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - DB_HOST=postgresql
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=false
    image: temporalio/auto-setup:1.22.4
    networks:
      - julep-network
    ports:
      - 7233:7233
    labels:
      kompose.volume.type: configMap
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

volumes:
  model_data:
    name: model_data
    external: true

networks:
  julep-network:
    driver: bridge
    name: julep-network
