name: julep
version: "3"

include:
  - ./memory-store/docker-compose.yml
  - ./model-serving/docker-compose.yml
  - ./gateway/docker-compose.yml
  - ./agents-api/docker-compose.yml

  # TODO: Enable after testing
  # - ./monitoring/docker-compose.yml
