name: julep
version: "3"

include:
  - ./cozo-server/docker-compose.yml
  - ./model-api/docker-compose.yml
  - ./agents-api/docker-compose.yml

services:
  reverse-proxy:
    image: traefik:v2.11
    command: 
      # - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --accesslog=true
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.domains[0].main=dev.julep.ai
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --certificatesresolvers.letsencrypt.acme.email=developers@julep.ai
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --providers.file.directory=/traefik_config
      - --providers.file.watch=true
      - --experimental.plugins.jwt.moduleName=github.com/julep-ai/traefik-jwt-plugin
      - --experimental.plugins.jwt.version=v0.0.1
      #
      # Only needed for debugging ssl certificates
      # - "--log.level=DEBUG"
      # - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"

    ports:
      - 443:443
      - 80:80
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_config:/traefik_config

    develop:
      watch:
        - action: sync+restart
          path: ./docker-compose.yml
          target: /tmp
