
---
version: "3.9"

services:
  samantha-backend:
    build:
      context: backend
      args:
        HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
    env_file: .env
    environment:
      PORT: "5000"
    ports:
      - '5000:5000'
    volumes:
      - user_cache:/root/.cache

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040

volumes:
  user_cache:
    name: user_cache
