name: prometheus

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    profiles:
      - multi-tenant

    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    
    depends_on:
      agents-api-multi-tenant:
        condition: service_started
    
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  prometheus_data:
    external: true
