name: julep-agents-api

# Shared environment variables
x--shared-environment: &shared-environment
  AGENTS_API_KEY: ${AGENTS_API_KEY}
  AGENTS_API_KEY_HEADER_NAME: ${AGENTS_API_KEY_HEADER_NAME:-Authorization}
  AGENTS_API_HOSTNAME: ${AGENTS_API_HOSTNAME:-localhost}
  AGENTS_API_PUBLIC_PORT: ${AGENTS_API_PUBLIC_PORT:-80}
  AGENTS_API_PROTOCOL: ${AGENTS_API_PROTOCOL:-http}
  AGENTS_API_URL: ${AGENTS_API_URL:-http://agents-api:8080}
  COZO_AUTH_TOKEN: ${COZO_AUTH_TOKEN}
  COZO_HOST: ${COZO_HOST:-http://memory-store:9070}
  DEBUG: ${AGENTS_API_DEBUG:-False}
  EMBEDDING_MODEL_ID: ${EMBEDDING_MODEL_ID:-Alibaba-NLP/gte-large-en-v1.5}
  INTEGRATION_SERVICE_URL: ${INTEGRATION_SERVICE_URL:-http://integrations:8000}
  LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
  LITELLM_URL: ${LITELLM_URL:-http://litellm:4000}
  SUMMARIZATION_MODEL_NAME: ${SUMMARIZATION_MODEL_NAME:-gpt-4-turbo}
  TEMPORAL_ENDPOINT: ${TEMPORAL_ENDPOINT:-temporal:7233}
  TEMPORAL_NAMESPACE: ${TEMPORAL_NAMESPACE:-default}
  TEMPORAL_TASK_QUEUE: ${TEMPORAL_TASK_QUEUE:-julep-task-queue}
  TEMPORAL_WORKER_URL: ${TEMPORAL_WORKER_URL:-temporal:7233}
  TRUNCATE_EMBED_TEXT: ${TRUNCATE_EMBED_TEXT:-True}
  WORKER_URL: ${WORKER_URL:-temporal:7233}
  USE_BLOB_STORE_FOR_TEMPORAL: ${USE_BLOB_STORE_FOR_TEMPORAL:-false}
  BLOB_STORE_CUTOFF_KB: ${BLOB_STORE_CUTOFF_KB:-1024}
  BLOB_STORE_BUCKET: ${BLOB_STORE_BUCKET:-agents-api}
  S3_ENDPOINT: ${S3_ENDPOINT:-http://seaweedfs:8333}
  S3_ACCESS_KEY: ${S3_ACCESS_KEY}
  S3_SECRET_KEY: ${S3_SECRET_KEY}

x--base-agents-api: &base-agents-api
  image: julepai/agents-api:${TAG:-dev}
  depends_on:
    worker:
      condition: service_started
  environment:
    <<: *shared-environment
  build:
    context: .
    dockerfile: Dockerfile

  ports:
    - "8080:8080"

  develop:
    watch:
      - action: sync+restart
        path: ./agents_api
        target: /app/agents_api
        ignore:
          - ./**/*.pyc
      - action: rebuild
        path: poetry.lock
      - action: rebuild
        path: Dockerfile


services:
  agents-api:
    <<: *base-agents-api
    profiles:
      - ''  # Acts as a default profile. See: https://stackoverflow.com/questions/75758174/how-to-make-profile-default-for-docker-compose
      - single-tenant

  agents-api-multi-tenant:
    <<: *base-agents-api
    profiles:
      - multi-tenant
    environment:
      <<: *shared-environment
      AGENTS_API_MULTI_TENANT_MODE: true
      AGENTS_API_PREFIX: "/api"

  worker:
    image: julepai/worker:${TAG:-dev}
    environment:
      <<: *shared-environment
    build:
      context: .
      dockerfile: Dockerfile.worker

    develop:
      watch:
        - action: sync+restart
          path: ./agents_api
          target: /app/agents_api
          ignore:
            - ./**/*.pyc
        - action: rebuild
          path: poetry.lock
        - action: rebuild
          path: Dockerfile.worker

  cozo-migrate:
    image: julepai/cozo-migrate:${TAG:-dev}
    container_name: cozo-migrate
    build:
      context: .
      dockerfile: Dockerfile.migration
    restart: "no" # Make sure to double quote this
    environment:
      <<: *shared-environment

    develop:
      watch:
        - action: sync+restart
          path: ./migrations
          target: /app/migrations
        - action: rebuild
          path: Dockerfile.migration
