name: julep-agents-api
version: "3"

include:
  - ../model-api/docker-compose.yml
  - ../cozo-server/docker-compose.yml

services:
  agents-api:
    env_file:
      - path: .env
        required: true
      - path: ../.env
        required: false

    container_name: agents-api
    depends_on:
      model-api:
        condition: service_started
      cozo-server:
        condition: service_started
      worker:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agents_api.rule=Path(`/api{path:.*}`)"
      #- "traefik.http.middlewares.agents_api-add_headers.headers.customrequestheaders.X-Developer-Id=00000000-0000-0000-0000-000000000000"
      #- "traefik.http.middlewares.agents_api-add_headers.headers.customrequestheaders.X-Developer-Email=developers@julep.ai"
      - "traefik.http.middlewares.agents_api-add_prefix.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.agents_api-add_prefix.stripprefix.forceSlash=false"
      - "traefik.http.middlewares.agents_api-chain.chain.middlewares=agents_api-add_prefix"
      #- "traefik.http.routers.agents_api.middlewares=agents_api-chain@docker,my-jwt@file"
      - "traefik.http.routers.agents_api.middlewares=agents_api-chain@docker"

    develop:
      watch:
        - action: sync+restart
          path: ./agents_api
          target: /app/agents_api
          ignore:
          - ./**/*.pyc
        - action: rebuild
          path: poetry.lock
        - action: rebuild
          path: Dockerfile

  worker:
    env_file:
      - path: .env
        required: true
      - path: ../.env
        required: false

    build:
      context: .
      dockerfile: Dockerfile.worker
    entrypoint: ["tail", "-f", "/dev/null"]
    depends_on:
      text-embeddings-inference:
        condition: service_started
      temporal:
        condition: service_started

    develop:
      watch:
        - action: sync+restart
          path: ./agents_api
          target: /app/agents_api
          ignore:
          - ./**/*.pyc
        - action: rebuild
          path: poetry.lock
        - action: rebuild
          path: Dockerfile.worker

  text-embeddings-inference:
    container_name: text-embeddings-inference
    env_file:
      - path: .env
        required: true
      - path: ../.env
        required: false

    image: ghcr.io/huggingface/text-embeddings-inference:1.0
    ports:
      - "8082:80"
    shm_size: "2gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  temporal:
    container_name: temporal
    env_file:
      - path: .env
        required: true
      - path: ../.env
        required: false

    build:
      context: .
      dockerfile: Dockerfile.temporal
    ports:
      - 7233:7233
    volumes:
      - temporal_data:/home/temporal

    develop:
      watch:
        - action: rebuild
          path: Dockerfile.temporal

  cozo-migrate:
    env_file:
      - path: .env
        required: true
      - path: ../.env
        required: false

    container_name: cozo-migrate
    depends_on:
      cozo-server:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile.migration
    restart: "no" # Make sure to double quote this

    develop:
      watch:
        - action: sync+restart
          path: ./migrations
          target: /app/migrations
        - action: rebuild
          path: Dockerfile.migration

volumes:
  temporal_data:
