[tool.poetry]
name = "agents-api"
version = "0.1.0"
description = ""
authors = ["Julep Developers <developers@julep.ai>"]
readme = "README.md"
packages = [{include = "agents_api"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
fastapi = "^0.110.1"
pycozo = {extras = ["embedded"], version = "^0.7.6"}
uvicorn = "^0.23.2"
fire = "^0.5.0"
environs = "^10.3.0"
google-cloud-aiplatform = "^1.33.0"
pandas = "^2.1.0"
openai = "^1.12.0"
httpx = "^0.26.0"
async-lru = "^2.0.4"
sentry-sdk = {extras = ["fastapi"], version = "^1.38.0"}
temporalio = "^1.4.0"
pydantic = "^2.5.3"
arrow = "^1.3.0"
jinja2 = "^3.1.3"
jinja2schema = "^0.1.4"
jsonschema = "^4.21.1"
litellm = "^1.35.32"
numpy = "^1.26.4"
transformers = "^4.40.1"
tiktoken = "^0.6.0"
xxhash = "^3.4.1"


[tool.poetry.group.dev.dependencies]
ipython = "^8.18.1"
black = "^24.4.0"
ruff = "^0.1.9"
datamodel-code-generator = "^0.25.3"
cozo-migrate = "^0.2.0"
poethepoet = "^0.25.1"
pytype = ">=2024.4.11"
julep = "^0.2.4"
pyjwt = "^2.8.0"
ward = "^0.68.0b0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
agents-api = "scripts.agents_api:run"

[tool.poe.tasks]
format = "black ."
lint = "ruff agents_api/**/*.py migrations/**/*.py tests/**/*.py --fix --unsafe-fixes"
typecheck = "pytype --config pytype.toml"
check = [
    "format",
    "lint",
    "typecheck",
]
test = "ward"
codegen = "datamodel-codegen --input ../openapi.yaml --input-file-type openapi --output agents_api/autogen/openapi_model.py --use-operation-id-as-name --use-double-quotes --use-schema-description --target-python-version 3.10 --reuse-model --collapse-root-models --use-field-description --field-include-all-keys --use-unique-items-as-set --use-subclass-enum --use-union-operator --use-one-literal-as-default --use-annotated --enum-field-as-literal one --output-model-type pydantic_v2.BaseModel"
