name: julep-monitoring

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    profiles:
      - multi-tenant

    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    
    depends_on:
      agents-api-multi-tenant:
        condition: service_started
    
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    profiles:
      - multi-tenant

volumes:
  prometheus_data:
    external: true
  grafana_data:
    external: true
