name: "🐛 Bug Report"
description: "Submit a bug report to help us improve"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "📜 Description"
      placeholder: "A clear and concise description of what the bug is."

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "👟 Reproduction steps"
      placeholder: "1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error"

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "👀 Have you searched previous issues to see if this has been raised before?"
      options:
        - label: "I checked and didn't find similar issue"
          required: true
