name: julep-model-serving

services:
  model-serving:
    image: julepai/model-serving:dev
    env_file: "../.env"

    environment:
      - MODEL_NAME=${MODEL_NAME}
      - MODEL_API_KEY=${MODEL_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - SENTRY_DSN=${SENTRY_DSN}
      - TP_SIZE=${TP_SIZE}
      - MAX_MODEL_LEN=${MAX_MODEL_LEN}
      - MAX_NUM_SEQS=${MAX_NUM_SEQS}
      - GPU_MEMORY_UTILIZATION=${GPU_MEMORY_UTILIZATION}
      - DTYPE=${DTYPE}
    container_name: model-serving
    build:
      context: .
      shm_size: "2gb"
    shm_size: "2gb"

    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface

    develop:
      watch:
        - action: sync+restart
          path: ./model_api
          target: /app/model_api
          ignore:
            - ./**/*.pyc
        - action: rebuild
          path: poetry.lock
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
