name: julep-scheduler

services:
  temporal:
    depends_on:
      temporal-db:
        condition: service_started
    environment:
      - DB=${TEMPORAL_POSTGRES_DB:-postgres12}
      - DB_PORT=${TEMPORAL_POSTGRES_PORT:-5432}
      - DB_HOST=${TEMPORAL_POSTGRES_HOST:-temporal-db}
      - POSTGRES_USER=${TEMPORAL_POSTGRES_USER:-temporal}
      - POSTGRES_PWD=${TEMPORAL_POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=temporal-db
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    image: temporalio/auto-setup:1.24
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-admin-tools:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.24
    stdin_open: true
    tty: true

  temporal-db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${TEMPORAL_POSTGRES_DB:-temporal}
      - POSTGRES_USER=${TEMPORAL_POSTGRES_USER:-temporal}
      - POSTGRES_PASSWORD=${TEMPORAL_POSTGRES_PASSWORD}
    volumes:
      - temporal-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${TEMPORAL_POSTGRES_DB:-temporal} -U ${TEMPORAL_POSTGRES_USER:-temporal}" ]

      interval: 1s
      timeout: 5s
      retries: 10

  temporal-ui:
    image: temporalio/ui:latest
    profiles:
      - temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - 9000:8080  # Since 8080 is already used by agents-api


volumes:
  temporal-db-data:
