name: julep-integrations

# Shared environment variables
x--shared-environment: &shared-environment
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  INTEGRATIONS_SERVICE_PORT: ${INTEGRATIONS_SERVICE_PORT:-8000}

services:
  integrations:
    image: julepai/integrations:${TAG:-dev}
    build: .
    
    environment:
      <<: *shared-environment
    
    ports:
      - "${INTEGRATIONS_SERVICE_PORT:-8000}:${INTEGRATIONS_SERVICE_PORT:-8000}" # map host to container port

    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app/
          ignore:
            - ./**/*.pyc
        - action: rebuild
          path: poetry.lock
        - action: rebuild
          path: Dockerfile
