global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 5s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 3s
      api_version: v1
scrape_configs:
  - job_name: traefik
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 3s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - gateway:8082
