name: julep-memory-store
version: "3"

services:
  memory-store:
    image: julepai/memory-store:dev
    env_file: "../.env"
    environment:
      - COZO_AUTH_TOKEN=${COZO_AUTH_TOKEN}
      - COZO_PORT=${COZO_PORT}
      - MNT_DIR=/data
    container_name: memory-store
    volumes:
      - cozo_data:/data
    build:
      context: .
    ports:
      - "9070:9070"

volumes:
  cozo_data:
