name: julep-memory-store
version: "3"

services:
  memory-store:
    env_file:
      - path: .env
        required: false
      - path: ../.env
        required: true
    environment:
      - COZO_AUTH_TOKEN=${COZO_AUTH_TOKEN}
      - COZO_PORT=${COZO_PORT}
      - MNT_DIR=/data
    container_name: memory-store
    volumes:
      - cozo_data:/data
    build:
      context: .
    ports:
      - "9070:9070"

volumes:
  cozo_data:
