name: julep-model-api

services:
  model-api:
    env_file:
      - path: .env
        required: false
      - path: ../.env
        required: true
    environment:
      - MODEL_API_KEY=${MODEL_API_KEY}
      - MODEL_API_KEY_HEADER_NAME=${MODEL_API_KEY_HEADER_NAME}
      - SKIP_CHECK_DEVELOPER_HEADERS=${SKIP_CHECK_DEVELOPER_HEADERS}
      - MODEL_NAME=${MODEL_NAME}
      - HF_TOKEN=${HF_TOKEN}
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - SENTRY_DSN=${SENTRY_DSN}
      - TP_SIZE=${TP_SIZE}
      - MAX_MODEL_LEN=${MAX_MODEL_LEN}
      - MAX_NUM_SEQS=${MAX_NUM_SEQS}
      - GPU_MEMORY_UTILIZATION=${GPU_MEMORY_UTILIZATION}
      - DTYPE=${DTYPE}
    container_name: model-api
    build:
      context: .
      shm_size: "2gb"
    shm_size: "2gb"

    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.default.rule=Path(`/v1{path:.*}`)"
      - "traefik.http.middlewares.model_api-add_headers.headers.customrequestheaders.X-Developer-Id=00000000-0000-0000-0000-000000000000"
      - "traefik.http.middlewares.model_api-add_headers.headers.customrequestheaders.X-Developer-Email=developers@julep.ai"
      - "traefik.http.middlewares.model_api-chain.chain.middlewares=model_api-add_headers"
      - "traefik.http.routers.model_api.middlewares=model_api-chain@docker"

    develop:
      watch:
        - action: sync+restart
          path: ./model_api
          target: /app/model_api
          ignore:
            - ./**/*.pyc
        - action: rebuild
          path: poetry.lock
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
