name: julep-model-api

services:
  model-api:
    env_file:
      - path: .env
        required: true
      - path: ../.env
        required: false
    environment:
      - API_KEY=${API_KEY}
      - API_KEY_HEADER_NAME=${API_KEY_HEADER_NAME}
      - SKIP_CHECK_DEVELOPER_HEADERS=${SKIP_CHECK_DEVELOPER_HEADERS}
      - MODEL_NAME=${MODEL_NAME}
      - HF_TOKEN=${HF_TOKEN}
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - SENTRY_DSN=${SENTRY_DSN}
    container_name: model-api
    build:
      context: .
      shm_size: "2gb"
    shm_size: "2gb"

    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.default.rule=Path(`/v1{path:.*}`)"
      - "traefik.http.middlewares.model_api-add_headers.headers.customrequestheaders.X-Developer-Id=de719a8a-446f-42c4-87e5-c19d83eabe40"
      - "traefik.http.middlewares.model_api-add_headers.headers.customrequestheaders.X-Developer-Email=developers@julep.ai"
      - "traefik.http.middlewares.model_api-chain.chain.middlewares=model_api-add_headers"
      - "traefik.http.routers.model_api.middlewares=model_api-chain@docker"

 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
