name: Changelog on release

on:
  release:
    types: [published]

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev

      # Generate changelog from release notes
      - uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request: true
      