name: Build and push images to docker hub on merge to dev
run-name: ${{ github.actor }} is building and pushing images to docker hub

on:
  push:
    branches:
      - "dev"

jobs:
  Bake-Push-Images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set branch name
        id: variables
        run: |
          echo "branch_name=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')" >> $GITHUB_OUTPUT
          echo "git_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: julepai
          password: "${{ secrets.DOCKER_HUB_PASSWORD }}"

      - name: Build and push agent images
        uses: docker/bake-action@v3
        with:
          files: |
            ./docker-bake.hcl
          targets: agents-api
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
            *.args.TAG=${{ steps.variables.outputs.branch_name }}
            *.args.GIT_SHA=${{ steps.variables.outputs.git_sha }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/dev' }}
