name: Bake images on PR
run-name: ${{ github.actor }} is baking images

on:
  pull_request:

jobs:
  Bake-Images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: julepai
          password: "${{ secrets.DOCKER_HUB_PASSWORD }}"

      - name: Bake images
        uses: docker/bake-action@v5
        with:
          files: |
            ./docker-bake.hcl
          targets: agents-api
          push: false
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
        env:
          TAG: pr-run-${{ github.run_number }}-${{ github.run_attempt }}
          GIT_SHA: ${{ github.sha }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
