name: Generate docs on merge to dev
run-name: ${{ github.actor }} is generating documentation

on:
  push:
    branches:
      - "dev"
      - "main"

jobs:
  Generate-Docs-For-TS-SDK:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: sdks/ts/node_modules
          key: ${{ runner.os }}-sdks-ts-npm-${{ hashFiles('sdks/ts/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-sdks-ts-npm-

      - name: Install npm dependencies
        run: |
          cd sdks/ts
          npm ci

      - name: Generate docs
        run: |
          cd sdks/ts
          npm run generate-docs

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "doc(sdks/ts): Generate docs for sdks/ts (CI)"
          branch: ${{ github.head_ref }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
