name: Lint and typecheck APIs and SDKs
run-name: ${{ github.actor }} is linting and typechecking the code

on: [pull_request]

jobs:
  Lint-And-Format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: [agents-api, model-serving, sdks/python]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Configure Poetry to use .venv
        run: |
          cd ${{ matrix.directory }}
          poetry config virtualenvs.in-project true

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        with:
          path: ${{ matrix.directory }}/.venv
          key: ${{ runner.os }}-${{ matrix.directory }}-poetry-${{ hashFiles(format('{0}/poetry.lock', matrix.directory)) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.directory }}-poetry-

      - name: Cache pytype
        uses: actions/cache@v4
        with:
          path: ${{ matrix.directory }}/.pytype
          key: ${{ runner.os }}-${{ matrix.directory }}-pytype-${{ hashFiles(format('{0}/**/*.py', matrix.directory)) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.directory }}-pytype-

      - name: Install dependencies
        run: |
          cd ${{ matrix.directory }}
          poetry install

      - name: Lint and format
        run: |
          cd ${{ matrix.directory }}
          poetry run poe format
          poetry run poe lint

      - name: Typecheck
        run: |
          cd ${{ matrix.directory }}
          poetry run poe typecheck

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "refactor: Lint ${{ matrix.directory }} (CI)"
          branch: ${{ github.head_ref }}

  Lint-And-Format-TS-SDK:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: sdks/ts/node_modules
          key: ${{ runner.os }}-sdks-ts-npm-${{ hashFiles('sdks/ts/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-sdks-ts-npm-

      - name: Install npm dependencies
        run: |
          cd sdks/ts
          npm ci

      - name: Lint and format TypeScript SDK
        run: |
          cd sdks/ts
          npm run format

      - name: Build TypeScript SDK
        run: |
          cd sdks/ts
          npm run build

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "refactor: Lint sdks/ts (CI)"
          branch: ${{ github.head_ref }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
