name: Lint and typecheck agents-api
run-name: ${{ github.actor }} is linting and typechecking the code

# TODO: Fix CI github actions
# SCRUM-26

on: [pull_request]

jobs:
  Lint-And-Format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Configure Poetry to use .venv
        run: |
          cd agents-api
          poetry config virtualenvs.in-project true

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        with:
          path: agents-api/.venv
          key: ${{ runner.os }}-agents-api-poetry-${{ hashFiles('agents-api/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-agents-api-poetry-

      - name: Install dependencies
        run: |
          cd agents-api
          poetry install

      - name: Lint and format
        run: |
          cd agents-api
          poetry run poe format
          poetry run poe lint

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "refactor: Lint agents-api (CI)"
          branch: ${{ github.head_ref }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
