name: Build and push images to docker hub on merge to dev
run-name: ${{ github.actor }} is building and pushing images to docker hub

on:
  push:
    branches:
      - "dev"

jobs:
  Build-Push-Images-To-Docker-Hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: julepai
          password: "${{ secrets.DOCKER_HUB_PASSWORD }}"

      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: "2.24.6"

      - name: Build images
        run: |
          touch .env
          docker compose build

      - name: Push images
        run: |
          docker compose push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
