name: Build and push images to docker hub on merge to dev
run-name: ${{ github.actor }} is building and pushing images to docker hub

on: [push]
# on:
#   push:
#     branches:
#       - "dev"

jobs:
  Build-Push-Other-Images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service-directory:
          - gateway
          - memory-store
          # - model-serving

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: julepai
          password: "${{ secrets.DOCKER_HUB_PASSWORD }}"

      - name: Build and push images
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service-directory }}
          push: true
          tags: julepai/${{ matrix.service-directory }}:${{ github.ref_name | replace('/', '--') }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # cache-from: |
          #   type=registry,ref=julepai/${{ matrix.service-directory }}:${{ github.ref_name | replace('/', '--') }}
          #   type=registry,ref=julepai/${{ matrix.service-directory }}:dev
          # cache-to: type=inline

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
