name: Translate ReadME

on:
  push:
    paths:
      - "README.md"

jobs:
  readme-translator:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python v3.10.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install deep-translator git+https://github.com/Jwink3101/parmapper

      - name: Run translator script
        run: python scripts/readme_translator.py

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README-*.md
          git commit -m "chore(readme): translate README.md"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
