name: Translate ReadME

on:
  push:
    paths:
      - "README.md"

jobs:
  readme-translator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python v3.10.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install deep-translator git+https://github.com/Jwink3101/parmapper

      - name: Run translator script
        run: python scripts/readme_translator.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(readme): translate README.md"
          title: "Translate README.md"
          body: "This PR updates the translated versions of README.md"
          branch: "translate-readme"
          delete-branch: true
          add-paths: |
            README.md
            README-*.md