name: Typecheck agents-api
run-name: ${{ github.actor }} is typechecking the code

on:
  pull_request:
    paths:
      - 'agents-api/**'
  push:
    paths:
      - 'agents-api/**'

jobs:
  Typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install libboost
        run: sudo apt-get install -y libboost-all-dev

      - name: Cache pytype
        uses: actions/cache@v4
        with:
          path: agents-api/.pytype
          key: ${{ runner.os }}-agents-api-pytype-${{ github.base_ref }}
          restore-keys: |
            ${{ runner.os }}-agents-api-pytype-

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up python and install dependencies
        run: |
          cd integrations-service
          uv python install
          uv sync --all-extras --dev

      - name: Typecheck
        run: |
          cd agents-api
          uv run poe typecheck

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
